[pytest]
addopts = -v -p reporting_plugin

markers =
    smoke: quick critical tests
    regression: full regression tests
    sanity: sanity level validation tests
    day21: day 21 pom integration tests
